version: 2.1
orbs:
  cypress: cypress-io/cypress@1.8.0
jobs:
  build:
    docker:
      - image: mamolli/cypress_awscli
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - deploy:
          name: Deploy DailyRoutine to production
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              npm run deploy
            fi
  cypress/run:
    start: npm start
    wait-on: 'http://localhost:3000'
