version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: 'npm install'
      - run:
          name: Run Linter
          command: 'npm run lint'
      - run:
          name: Run Unit Tests
          command: 'npm test'
      - run:
          name: Build Application
          command: 'npm build'
