version: 2
jobs:
  build:
    docker:
      - image: cypress/base:8
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: 'npm install'
      - run:
          name: Run Linter
          command: 'npm run lint'
      - run:
          name: Run Unit Tests
          command: 'npm test'
      - run:
          name: Build Application
          command: 'npm run build'
      - run:
          name: Run E2E tests on release ready code
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              npm run e2e
            fi
      - deploy:
          name: Deploy DailyRoutine to GitHub Pages
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "Perform deployment script"
            fi
