version: 2
jobs:
  build:
    docker:
      - image: cypress/base:8
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: 'npm install'
      - run:
          name: Run Linter
          command: 'npm run lint'
      - run:
          name: Code Formatting Check
          command: 'npm run format:check'
      - run:
          name: Run Unit Tests
          command: 'npm test'
      - run:
          name: Perform Test Application Build
          command: 'npm run build'
      - run:
          name: Run E2E tests on release ready code
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              npm run e2e
            fi
  deploy:
    docker:
      - image: circleci/python:2.7-jessie
    working_directory: ~/repo
    steps:
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Deploy DailyRoutine to GitHub Pages
          command: |
            if [ "${CIRCLE_BRANCH}" == "feature/DR17-deployment-aws" ]; then
              npm run deploy
            fi
