version: 2.1
orbs:
  cypress: cypress-io/cypress@1.8.0
jobs:
  test:
    docker:
      - image: mamolli/cypress_awscli
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Linter
          command: npm run lint
      - run:
          name: Code Formatting Check
          command: npm run format:check
      - run:
          name: Run Unit Tests With Code Coverage
          command: npm run test:ci
      - run:
          name: Install codecov
          command: npm install -g codecov
      - run:
          name: Upload Coverage Report to Codecov
          command: codecov
      - save_cache:
          paths:
            - /root/repo/node_modules
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
  deploy:
    docker:
      - image: mamolli/cypress_awscli
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
            keys:
              - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
              - node-v1-{{ .Branch }}-
              - node-v1-
      - run:
          name: Perform Test Application Build
          command: 'npm run build'
      - deploy:
          name: Deploy DailyRoutine to production
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              npm run deploy
            fi
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
#      - cypress/run:
#          start: npm start
#          wait-on: 'http://localhost:3000'
      - deploy:
          requires:
            - test
