version: 2
jobs:
  build:
    docker:
      - image: mamolli/cypress_awscli 
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: 'npm install'
      - run:
          name: Run Linter
          command: 'npm run lint'
      - run:
          name: Code Formatting Check
          command: 'npm run format:check'
      - run:
          name: Run Unit Tests
          command: 'npm test'
      - run:
          name: Run E2E tests on release ready code
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              npm run e2e
            fi
      - run:
          name: Perform Test Application Build
          command: 'npm run build'
      - deploy:
          name: Deploy DailyRoutine to GitHub Pages
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              npm run deploy
            fi
